(in-package :homepage)

(defview root (age)
  (declare (type fixnum age))
  (doctype-html)
  (html ()
    (head () (title () "Brian Belleville"))
  (body ()
    (h1 () "Welcome to the homepage of Brian Belleville")
    (img (:src "/face.jpeg" :alt "portrait"))
    (p ()
      "Welcome to my home page, this site was " (strong () "generated and served")
      " by a web application layer " (strong () "entirely written by me")
      ". The code for this site and this server was written in " (strong ()
								   "Common Lisp")
      ". The code for this site is available on "
      (strong () (a (:href "https://github.com/BrianBelleville/bel-serve") "GitHub"))
      ". This includes the code for the " (strong () (a (:href "https://github.com/BrianBelleville/bel-serve") "http server"))
      ", the " (strong () (a (:href "https://github.com/BrianBelleville/first-gen")
			"web framework"))
      ", and the " (strong () (a (:href "https://github.com/BrianBelleville/homepage") "website itself")) ".")
    (p ()
      "I am currently " age " years old and employed at " (strong () "Western Digital") " in Southern California, here is my " (strong () (a (:href "/resume.pdf") "Resume")) ". In case you were wondering I will not be manually updating my age each year."))))